const charactersLunatic = [
	{
		"img":"/assets/img/characters/cirnolunatic1.gif",
		"id":1
	},
	{
		"img":"/assets/img/characters/cirnolunatic2.gif",
		"id":2
	},
	{
		"img":"/assets/img/characters/cirnoside1.gif",
		"id":3
	},
	{
		"img":"/assets/img/characters/cirnoside2.gif",
		"id":4
	},
	{
		"img":"/assets/img/characters/cirno1.gif",
		"id":5
	},
	{
		"img":"/assets/img/characters/cirnospin1.gif",
		"id":6
	},
	{
		"img":"/assets/img/characters/cirnospin2.gif",
		"id":7
	},
	{
		"img":"/assets/img/characters/cirnoup1.gif",
		"id":8
	},
	{
		"img":"/assets/img/characters/cirnoup2.gif",
		"id":9
	}
]

export default charactersLunatic;